### ISSUE TITLE
Caption inline CSS being removed

### ISSUE THREAD

**Issue by strmtrpr83** [UCF/Athena-Shortcodes-Plugin#44]
The inline width CSS that WordPress generally adds to a **figcaption's** parent **figure** field is missing. Without the width being defined on the parent **figure** it's causing long caption text to expand past the width of the image which causes layout issues. It appears to be overwritten when the format_caption_shortcode function is run via the img_caption_shortcode hook. It may be possible to resolve this by having this hook run at a different time. This appears function and hook appear to be firing after WordPress adds in the inline CSS which is removing the inline CSS.

**Comment by strmtrpr83** [comment]
Ok, it looks like there's an easy fix for this. There is a 'width' shortcode attribute that gets passed into format_caption_shortcode via $attr but is not used. Please forgive the formatting and feel free to add any extra sanitization.
You could change the $atts declaration up top to
`'$atts = shortcode_atts( array(
	'id'	  => '',
	'align'	  => '',
	'width'	  => '',
	'caption' => '',
	'class'   => '',
), $attr, 'caption' );`
add a conditional check to see if there is a width value and update $atts['width'] accordingly.
`if ( ! empty( $atts['width'] ) ){
	$atts['width'] = 'max-width:'.$atts['width'].'px;';
}`
and add the inline css to the if / else that checks for $html5
`if ( $html5 ) {
	$html = '<figure ' . $atts['id'] . ' style="' . $atts['width'] . '" class="' . esc_attr( $class ) . '">'
	. do_shortcode( $content ) . '<figcaption class="figure-caption">' . $atts['caption'] . '</figcaption></figure>';
} else {
	$html = '<div ' . $atts['id'] . ' style="' . $atts['width'] . '" class="' . esc_attr( $class ) . '">'
	. do_shortcode( $content ) . '<p class="figure-caption">' . $atts['caption'] . '</p></div>';
}`

**Comment by cjg89** [comment]
`max-width` has been added to `<figure>` elements in v0.3.1.
